<?php

namespace Database\Seeders;

use App\Models\InventoryItem;
use Illuminate\Database\Seeder;

class InventoryDummySeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            ['asset_tag' => 'ASSET-001', 'item_name' => 'Laptop', 'category' => 'Electronics', 'brand' => 'Dell', 'model' => 'Latitude 5440', 'serial_number' => 'DL-5440-001', 'purchase_date' => '2024-01-10', 'warranty_expiry' => '2027-01-10', 'assigned_to' => 'Juan Dela Cruz', 'department' => 'IT', 'campaign' => 'HQ-IT', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'For daily operations', 'quantity' => 2],
            ['asset_tag' => 'ASSET-002', 'item_name' => 'Laptop', 'category' => 'Electronics', 'brand' => 'HP', 'model' => 'ProBook 450', 'serial_number' => 'HP-450-002', 'purchase_date' => '2024-02-12', 'warranty_expiry' => '2027-02-12', 'assigned_to' => 'Maria Santos', 'department' => 'Finance', 'campaign' => 'FIN-OPS', 'location' => 'Branch Office', 'status' => 'Available', 'remarks' => 'Finance department asset', 'quantity' => 3],
            ['asset_tag' => 'ASSET-003', 'item_name' => 'Monitor', 'category' => 'Electronics', 'brand' => 'LG', 'model' => '24MP59G', 'serial_number' => 'LG-24-003', 'purchase_date' => '2023-11-20', 'warranty_expiry' => '2026-11-20', 'assigned_to' => 'Rina Gomez', 'department' => 'HR', 'campaign' => 'HR-SETUP', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'HR workstation', 'quantity' => 4],
            ['asset_tag' => 'ASSET-004', 'item_name' => 'Printer', 'category' => 'Office Equipment', 'brand' => 'Canon', 'model' => 'MF 445dw', 'serial_number' => 'CN-445-004', 'purchase_date' => '2023-09-15', 'warranty_expiry' => '2026-09-15', 'assigned_to' => 'Mark Rivera', 'department' => 'Admin', 'campaign' => 'ADMIN-PRINTER', 'location' => 'Warehouse', 'status' => 'Available', 'remarks' => 'Shared printer', 'quantity' => 2],
            ['asset_tag' => 'ASSET-005', 'item_name' => 'Projector', 'category' => 'Electronics', 'brand' => 'Epson', 'model' => 'EB-X06', 'serial_number' => 'EP-006-005', 'purchase_date' => '2024-03-18', 'warranty_expiry' => '2027-03-18', 'assigned_to' => 'Alicia Tan', 'department' => 'Operations', 'campaign' => 'OPS-TRAINING', 'location' => 'Training Room', 'status' => 'Available', 'remarks' => 'Used for presentations', 'quantity' => 1],
            ['asset_tag' => 'ASSET-006', 'item_name' => 'UPS', 'category' => 'Power', 'brand' => 'APC', 'model' => 'Back-UPS 950', 'serial_number' => 'APC-950-006', 'purchase_date' => '2024-04-22', 'warranty_expiry' => '2027-04-22', 'assigned_to' => 'Nikki Cruz', 'department' => 'IT', 'campaign' => 'IT-POWER', 'location' => 'Server Room', 'status' => 'Available', 'remarks' => 'Backup power support', 'quantity' => 5],
            ['asset_tag' => 'ASSET-007', 'item_name' => 'Keyboard', 'category' => 'Accessories', 'brand' => 'Logitech', 'model' => 'K380', 'serial_number' => 'LG-380-007', 'purchase_date' => '2024-05-02', 'warranty_expiry' => '2027-05-02', 'assigned_to' => 'Leo Bautista', 'department' => 'Sales', 'campaign' => 'SALES-TOOLKIT', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Wireless keyboard', 'quantity' => 10],
            ['asset_tag' => 'ASSET-008', 'item_name' => 'Mouse', 'category' => 'Accessories', 'brand' => 'Logitech', 'model' => 'M185', 'serial_number' => 'LG-M185-008', 'purchase_date' => '2024-05-05', 'warranty_expiry' => '2027-05-05', 'assigned_to' => 'Joan Salazar', 'department' => 'Sales', 'campaign' => 'SALES-TOOLKIT', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Office accessories', 'quantity' => 12],
            ['asset_tag' => 'ASSET-009', 'item_name' => 'Router', 'category' => 'Networking', 'brand' => 'TP-Link', 'model' => 'TL-WR841N', 'serial_number' => 'TP-841-009', 'purchase_date' => '2023-12-09', 'warranty_expiry' => '2026-12-09', 'assigned_to' => 'Carl Martinez', 'department' => 'IT', 'campaign' => 'NET-SETUP', 'location' => 'Branch Office', 'status' => 'Available', 'remarks' => 'Branch internet', 'quantity' => 2],
            ['asset_tag' => 'ASSET-010', 'item_name' => 'Switch', 'category' => 'Networking', 'brand' => 'Cisco', 'model' => 'SG110-24', 'serial_number' => 'CS-110-010', 'purchase_date' => '2024-01-27', 'warranty_expiry' => '2027-01-27', 'assigned_to' => 'Diana Yu', 'department' => 'IT', 'campaign' => 'NET-SETUP', 'location' => 'Server Room', 'status' => 'Available', 'remarks' => 'Network switch', 'quantity' => 3],
            ['asset_tag' => 'ASSET-011', 'item_name' => 'Desk Chair', 'category' => 'Furniture', 'brand' => 'Flexi', 'model' => 'Ergo Pro', 'serial_number' => 'FX-ERG-011', 'purchase_date' => '2024-06-01', 'warranty_expiry' => '2029-06-01', 'assigned_to' => 'Rosemarie Lim', 'department' => 'Admin', 'campaign' => 'OFFICE-REFIT', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Office furniture', 'quantity' => 4],
            ['asset_tag' => 'ASSET-012', 'item_name' => 'Office Table', 'category' => 'Furniture', 'brand' => 'IKEA', 'model' => 'MALM', 'serial_number' => 'IK-MAL-012', 'purchase_date' => '2023-08-28', 'warranty_expiry' => '2028-08-28', 'assigned_to' => 'Elijah Scott', 'department' => 'Operations', 'campaign' => 'OFFICE-REFIT', 'location' => 'Warehouse', 'status' => 'Available', 'remarks' => 'Workstation table', 'quantity' => 6],
            ['asset_tag' => 'ASSET-013', 'item_name' => 'Scanner', 'category' => 'Office Equipment', 'brand' => 'Brother', 'model' => 'ADS-2700W', 'serial_number' => 'BR-2700-013', 'purchase_date' => '2024-02-14', 'warranty_expiry' => '2027-02-14', 'assigned_to' => 'Paula Reyes', 'department' => 'Admin', 'campaign' => 'DOCS-SETUP', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Document scanning', 'quantity' => 2],
            ['asset_tag' => 'ASSET-014', 'item_name' => 'Camera', 'category' => 'Security', 'brand' => 'Sony', 'model' => 'FDR-AX43', 'serial_number' => 'SN-AX43-014', 'purchase_date' => '2023-10-10', 'warranty_expiry' => '2026-10-10', 'assigned_to' => 'Cesar Flores', 'department' => 'Security', 'campaign' => 'SECURITY-OPS', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Security recording', 'quantity' => 1],
            ['asset_tag' => 'ASSET-015', 'item_name' => 'Tablet', 'category' => 'Electronics', 'brand' => 'Samsung', 'model' => 'Tab A8', 'serial_number' => 'SA-TAB-015', 'purchase_date' => '2024-06-11', 'warranty_expiry' => '2027-06-11', 'assigned_to' => 'Bea Lim', 'department' => 'Marketing', 'campaign' => 'MKT-TEAM', 'location' => 'Marketing Office', 'status' => 'Available', 'remarks' => 'Field marketing use', 'quantity' => 4],
            ['asset_tag' => 'ASSET-016', 'item_name' => 'Phone', 'category' => 'Communication', 'brand' => 'Samsung', 'model' => 'A54', 'serial_number' => 'SA-A54-016', 'purchase_date' => '2024-03-09', 'warranty_expiry' => '2027-03-09', 'assigned_to' => 'Noel Tan', 'department' => 'Support', 'campaign' => 'SUPPORT-TEAM', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Support communication', 'quantity' => 8],
            ['asset_tag' => 'ASSET-017', 'item_name' => 'External HDD', 'category' => 'Storage', 'brand' => 'Seagate', 'model' => '2TB Backup Plus', 'serial_number' => 'ST-2TB-017', 'purchase_date' => '2024-01-29', 'warranty_expiry' => '2027-01-29', 'assigned_to' => 'Harold Ramos', 'department' => 'IT', 'campaign' => 'IT-BACKUP', 'location' => 'Server Room', 'status' => 'Available', 'remarks' => 'Backup storage', 'quantity' => 6],
            ['asset_tag' => 'ASSET-018', 'item_name' => 'Webcam', 'category' => 'Accessories', 'brand' => 'Logitech', 'model' => 'C920', 'serial_number' => 'LG-C920-018', 'purchase_date' => '2024-05-18', 'warranty_expiry' => '2027-05-18', 'assigned_to' => 'Katrina Woo', 'department' => 'HR', 'campaign' => 'HR-SETUP', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Virtual meetings', 'quantity' => 5],
            ['asset_tag' => 'ASSET-019', 'item_name' => 'Speaker', 'category' => 'Audio', 'brand' => 'JBL', 'model' => 'Go 3', 'serial_number' => 'JB-GO-019', 'purchase_date' => '2024-06-16', 'warranty_expiry' => '2027-06-16', 'assigned_to' => 'Alfred Cruz', 'department' => 'Marketing', 'campaign' => 'MKT-TEAM', 'location' => 'Marketing Office', 'status' => 'Available', 'remarks' => 'Presentation audio', 'quantity' => 3],
            ['asset_tag' => 'ASSET-020', 'item_name' => 'Air Conditioner', 'category' => 'Facilities', 'brand' => 'Midea', 'model' => 'Inverter 1HP', 'serial_number' => 'MD-INV-020', 'purchase_date' => '2023-07-22', 'warranty_expiry' => '2026-07-22', 'assigned_to' => 'Tess Anonuevo', 'department' => 'Facilities', 'campaign' => 'FAC-OPERATIONS', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Cooling unit', 'quantity' => 2],
            ['asset_tag' => 'ASSET-021', 'item_name' => 'Label Printer', 'category' => 'Office Equipment', 'brand' => 'Zebra', 'model' => 'ZT230', 'serial_number' => 'ZB-230-021', 'purchase_date' => '2024-04-19', 'warranty_expiry' => '2027-04-19', 'assigned_to' => 'Benny Sapio', 'department' => 'Warehouse', 'campaign' => 'WH-LOGISTICS', 'location' => 'Warehouse', 'status' => 'Available', 'remarks' => 'Warehouse labeling', 'quantity' => 2],
            ['asset_tag' => 'ASSET-022', 'item_name' => 'Barcode Scanner', 'category' => 'Office Equipment', 'brand' => 'Honeywell', 'model' => 'Granite 1910', 'serial_number' => 'HW-1910-022', 'purchase_date' => '2024-02-20', 'warranty_expiry' => '2027-02-20', 'assigned_to' => 'Sonia Lee', 'department' => 'Warehouse', 'campaign' => 'WH-LOGISTICS', 'location' => 'Warehouse', 'status' => 'Available', 'remarks' => 'Inventory scanning', 'quantity' => 4],
            ['asset_tag' => 'ASSET-023', 'item_name' => 'Generator', 'category' => 'Power', 'brand' => 'Honda', 'model' => 'EU2200i', 'serial_number' => 'HN-2200-023', 'purchase_date' => '2023-11-15', 'warranty_expiry' => '2026-11-15', 'assigned_to' => 'Emil Reyes', 'department' => 'Facilities', 'campaign' => 'FAC-OPERATIONS', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Emergency power', 'quantity' => 1],
            ['asset_tag' => 'ASSET-024', 'item_name' => 'Portable Fan', 'category' => 'Facilities', 'brand' => 'Crompton', 'model' => 'High Speed', 'serial_number' => 'CR-FAN-024', 'purchase_date' => '2024-07-08', 'warranty_expiry' => '2027-07-08', 'assigned_to' => 'Connie Ortega', 'department' => 'Facilities', 'campaign' => 'FAC-OPERATIONS', 'location' => 'Branch Office', 'status' => 'Available', 'remarks' => 'Cooling support', 'quantity' => 6],
            ['asset_tag' => 'ASSET-025', 'item_name' => 'Desk Lamp', 'category' => 'Accessories', 'brand' => 'Philips', 'model' => 'Smart LED', 'serial_number' => 'PH-LED-025', 'purchase_date' => '2024-05-28', 'warranty_expiry' => '2027-05-28', 'assigned_to' => 'Jade Paloma', 'department' => 'Finance', 'campaign' => 'FIN-OPS', 'location' => 'Branch Office', 'status' => 'Available', 'remarks' => 'Workspace lighting', 'quantity' => 8],
            ['asset_tag' => 'ASSET-026', 'item_name' => 'USB Hub', 'category' => 'Accessories', 'brand' => 'Anker', 'model' => '7-in-1', 'serial_number' => 'AK-HUB-026', 'purchase_date' => '2024-06-18', 'warranty_expiry' => '2027-06-18', 'assigned_to' => 'Bobby Gomez', 'department' => 'IT', 'campaign' => 'IT-SETUP', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Device expansion', 'quantity' => 10],
            ['asset_tag' => 'ASSET-027', 'item_name' => 'Docking Station', 'category' => 'Accessories', 'brand' => 'Dell', 'model' => 'WD19', 'serial_number' => 'DL-WD19-027', 'purchase_date' => '2024-04-01', 'warranty_expiry' => '2027-04-01', 'assigned_to' => 'Ann Marie', 'department' => 'IT', 'campaign' => 'IT-SETUP', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Laptop docking', 'quantity' => 3],
            ['asset_tag' => 'ASSET-028', 'item_name' => 'Hard Drive Enclosure', 'category' => 'Storage', 'brand' => 'Sabrent', 'model' => 'USB 3.0', 'serial_number' => 'SB-USB-028', 'purchase_date' => '2023-12-11', 'warranty_expiry' => '2026-12-11', 'assigned_to' => 'Ritz Gomez', 'department' => 'IT', 'campaign' => 'IT-BACKUP', 'location' => 'Server Room', 'status' => 'Available', 'remarks' => 'Drive backup support', 'quantity' => 7],
            ['asset_tag' => 'ASSET-029', 'item_name' => 'Safety Helmet', 'category' => 'Safety', 'brand' => '3M', 'model' => 'V-Gard', 'serial_number' => '3M-HELM-029', 'purchase_date' => '2024-01-15', 'warranty_expiry' => '2027-01-15', 'assigned_to' => 'Nico Dela Torre', 'department' => 'Security', 'campaign' => 'SECURITY-OPS', 'location' => 'Warehouse', 'status' => 'Available', 'remarks' => 'Safety gear', 'quantity' => 9],
            ['asset_tag' => 'ASSET-030', 'item_name' => 'Fire Extinguisher', 'category' => 'Safety', 'brand' => 'Fireguard', 'model' => '5kg', 'serial_number' => 'FG-5KG-030', 'purchase_date' => '2023-09-01', 'warranty_expiry' => '2028-09-01', 'assigned_to' => 'Mika Santos', 'department' => 'Facilities', 'campaign' => 'FAC-OPERATIONS', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Emergency safety', 'quantity' => 3],
            ['asset_tag' => 'ASSET-031', 'item_name' => 'Vacuum Cleaner', 'category' => 'Facilities', 'brand' => 'Philips', 'model' => 'PowerPro', 'serial_number' => 'PH-VC-031', 'purchase_date' => '2024-04-10', 'warranty_expiry' => '2027-04-10', 'assigned_to' => 'Gene Ramos', 'department' => 'Facilities', 'campaign' => 'FAC-OPERATIONS', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Cleaning equipment', 'quantity' => 2],
            ['asset_tag' => 'ASSET-032', 'item_name' => 'Desk Fan', 'category' => 'Facilities', 'brand' => 'Hanabishi', 'model' => 'Air Breeze', 'serial_number' => 'HB-FAN-032', 'purchase_date' => '2024-05-10', 'warranty_expiry' => '2027-05-10', 'assigned_to' => 'Liza Santos', 'department' => 'Operations', 'campaign' => 'OPS-TRAINING', 'location' => 'Training Room', 'status' => 'Available', 'remarks' => 'Ventilation support', 'quantity' => 5],
            ['asset_tag' => 'ASSET-033', 'item_name' => 'Whiteboard', 'category' => 'Furniture', 'brand' => 'Nobo', 'model' => 'Magnetic Board', 'serial_number' => 'NB-WB-033', 'purchase_date' => '2024-03-29', 'warranty_expiry' => '2027-03-29', 'assigned_to' => 'Kevin Santos', 'department' => 'Operations', 'campaign' => 'OPS-TRAINING', 'location' => 'Training Room', 'status' => 'Available', 'remarks' => 'Training board', 'quantity' => 2],
            ['asset_tag' => 'ASSET-034', 'item_name' => 'Filing Cabinet', 'category' => 'Furniture', 'brand' => 'Steelcase', 'model' => '4 Drawer', 'serial_number' => 'SC-FC-034', 'purchase_date' => '2023-07-18', 'warranty_expiry' => '2026-07-18', 'assigned_to' => 'Mara Cruz', 'department' => 'Admin', 'campaign' => 'ADMIN-PRINTER', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Document storage', 'quantity' => 4],
            ['asset_tag' => 'ASSET-035', 'item_name' => 'Laser Pointer', 'category' => 'Accessories', 'brand' => 'Epson', 'model' => 'P-10', 'serial_number' => 'EP-LP-035', 'purchase_date' => '2024-05-30', 'warranty_expiry' => '2027-05-30', 'assigned_to' => 'Craig Tan', 'department' => 'Marketing', 'campaign' => 'MKT-TEAM', 'location' => 'Marketing Office', 'status' => 'Available', 'remarks' => 'Presentation tool', 'quantity' => 6],
            ['asset_tag' => 'ASSET-036', 'item_name' => 'Portable SSD', 'category' => 'Storage', 'brand' => 'SanDisk', 'model' => '1TB Extreme', 'serial_number' => 'SD-EXT-036', 'purchase_date' => '2024-02-06', 'warranty_expiry' => '2027-02-06', 'assigned_to' => 'Janice Lim', 'department' => 'IT', 'campaign' => 'IT-BACKUP', 'location' => 'Server Room', 'status' => 'Available', 'remarks' => 'Fast storage', 'quantity' => 5],
            ['asset_tag' => 'ASSET-037', 'item_name' => 'Network Cable', 'category' => 'Networking', 'brand' => 'Belkin', 'model' => 'Cat6', 'serial_number' => 'BK-CAT6-037', 'purchase_date' => '2024-03-15', 'warranty_expiry' => '2027-03-15', 'assigned_to' => 'Delia Villanueva', 'department' => 'IT', 'campaign' => 'NET-SETUP', 'location' => 'Warehouse', 'status' => 'Available', 'remarks' => 'Cable stock', 'quantity' => 20],
            ['asset_tag' => 'ASSET-038', 'item_name' => 'Telephone', 'category' => 'Communication', 'brand' => 'Panasonic', 'model' => 'KX-TS', 'serial_number' => 'PN-TS-038', 'purchase_date' => '2023-10-03', 'warranty_expiry' => '2026-10-03', 'assigned_to' => 'Glen Santos', 'department' => 'Admin', 'campaign' => 'ADMIN-PRINTER', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Office telephone', 'quantity' => 3],
            ['asset_tag' => 'ASSET-039', 'item_name' => 'Charging Cart', 'category' => 'Electronics', 'brand' => 'Kensington', 'model' => 'Mobile Cart', 'serial_number' => 'KN-CART-039', 'purchase_date' => '2024-05-22', 'warranty_expiry' => '2027-05-22', 'assigned_to' => 'Lorraine Dizon', 'department' => 'Operations', 'campaign' => 'OPS-TRAINING', 'location' => 'Training Room', 'status' => 'Available', 'remarks' => 'Device charging', 'quantity' => 2],
            ['asset_tag' => 'ASSET-040', 'item_name' => 'Conference Phone', 'category' => 'Communication', 'brand' => 'Poly', 'model' => 'CCX 400', 'serial_number' => 'PL-CCX-040', 'purchase_date' => '2024-06-20', 'warranty_expiry' => '2027-06-20', 'assigned_to' => 'Ralph Perez', 'department' => 'Operations', 'campaign' => 'OPS-TRAINING', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Conference communication', 'quantity' => 2],
            ['asset_tag' => 'ASSET-041', 'item_name' => 'Photo Printer', 'category' => 'Office Equipment', 'brand' => 'Canon', 'model' => 'Selphy', 'serial_number' => 'CN-SEL-041', 'purchase_date' => '2024-02-18', 'warranty_expiry' => '2027-02-18', 'assigned_to' => 'Nina Cruz', 'department' => 'Marketing', 'campaign' => 'MKT-TEAM', 'location' => 'Marketing Office', 'status' => 'Available', 'remarks' => 'Photo printing', 'quantity' => 1],
            ['asset_tag' => 'ASSET-042', 'item_name' => 'Bookshelf', 'category' => 'Furniture', 'brand' => 'Mainstays', 'model' => 'Open Shelf', 'serial_number' => 'MS-SHELF-042', 'purchase_date' => '2023-08-07', 'warranty_expiry' => '2028-08-07', 'assigned_to' => 'Pat Rivera', 'department' => 'Admin', 'campaign' => 'OFFICE-REFIT', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Storage shelf', 'quantity' => 3],
            ['asset_tag' => 'ASSET-043', 'item_name' => 'Wall Clock', 'category' => 'Furniture', 'brand' => 'Morris', 'model' => 'Classic', 'serial_number' => 'MR-WC-043', 'purchase_date' => '2024-04-21', 'warranty_expiry' => '2027-04-21', 'assigned_to' => 'Vera Moreno', 'department' => 'Admin', 'campaign' => 'OFFICE-REFIT', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Office wall clock', 'quantity' => 4],
            ['asset_tag' => 'ASSET-044', 'item_name' => 'Water Dispenser', 'category' => 'Facilities', 'brand' => 'AquaPure', 'model' => 'Hot Cold', 'serial_number' => 'AQ-DISP-044', 'purchase_date' => '2024-01-09', 'warranty_expiry' => '2027-01-09', 'assigned_to' => 'Theo Sison', 'department' => 'Facilities', 'campaign' => 'FAC-OPERATIONS', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Water station', 'quantity' => 1],
            ['asset_tag' => 'ASSET-045', 'item_name' => 'Portable Speaker', 'category' => 'Audio', 'brand' => 'JBL', 'model' => 'Charge 4', 'serial_number' => 'JB-CH4-045', 'purchase_date' => '2024-06-25', 'warranty_expiry' => '2027-06-25', 'assigned_to' => 'Alvin Ferrer', 'department' => 'Sales', 'campaign' => 'SALES-TOOLKIT', 'location' => 'Sales Office', 'status' => 'Available', 'remarks' => 'Sales events', 'quantity' => 3],
            ['asset_tag' => 'ASSET-046', 'item_name' => 'Laptop Stand', 'category' => 'Accessories', 'brand' => 'Rain Design', 'model' => 'mStand', 'serial_number' => 'RD-MST-046', 'purchase_date' => '2024-03-12', 'warranty_expiry' => '2027-03-12', 'assigned_to' => 'Mia Reyes', 'department' => 'Finance', 'campaign' => 'FIN-OPS', 'location' => 'Branch Office', 'status' => 'Available', 'remarks' => 'Laptop accessory', 'quantity' => 7],
            ['asset_tag' => 'ASSET-047', 'item_name' => 'Monitor Arm', 'category' => 'Accessories', 'brand' => 'Ergotron', 'model' => 'LX Arm', 'serial_number' => 'EG-LX-047', 'purchase_date' => '2024-04-07', 'warranty_expiry' => '2027-04-07', 'assigned_to' => 'Louise Diaz', 'department' => 'HR', 'campaign' => 'HR-SETUP', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Display mount', 'quantity' => 5],
            ['asset_tag' => 'ASSET-048', 'item_name' => 'Electric Kettle', 'category' => 'Facilities', 'brand' => 'Philips', 'model' => 'Cordless', 'serial_number' => 'PH-KTL-048', 'purchase_date' => '2024-05-21', 'warranty_expiry' => '2027-05-21', 'assigned_to' => 'Ella Dela Rosa', 'department' => 'Admin', 'campaign' => 'ADMIN-PRINTER', 'location' => 'Main Office', 'status' => 'Available', 'remarks' => 'Office pantry', 'quantity' => 2],
            ['asset_tag' => 'ASSET-049', 'item_name' => 'Portable Projector', 'category' => 'Electronics', 'brand' => 'BenQ', 'model' => 'GV31', 'serial_number' => 'BQ-GV31-049', 'purchase_date' => '2024-02-11', 'warranty_expiry' => '2027-02-11', 'assigned_to' => 'Ruben Gomez', 'department' => 'Operations', 'campaign' => 'OPS-TRAINING', 'location' => 'Training Room', 'status' => 'Available', 'remarks' => 'Mobile presentation', 'quantity' => 1],
            ['asset_tag' => 'ASSET-050', 'item_name' => 'Safety Vest', 'category' => 'Safety', 'brand' => 'Hi-Vis', 'model' => 'Reflective', 'serial_number' => 'HV-REF-050', 'purchase_date' => '2024-06-05', 'warranty_expiry' => '2027-06-05', 'assigned_to' => 'Cathy Tan', 'department' => 'Security', 'campaign' => 'SECURITY-OPS', 'location' => 'Warehouse', 'status' => 'Available', 'remarks' => 'Safety gear', 'quantity' => 10],
        ];

        foreach ($items as $item) {
            InventoryItem::create([
                'asset_tag' => $item['asset_tag'],
                'item_name' => $item['item_name'],
                'category' => $item['category'],
                'brand' => $item['brand'],
                'model' => $item['model'],
                'serial_number' => $item['serial_number'],
                'purchase_date' => $item['purchase_date'],
                'warranty_expiry' => $item['warranty_expiry'],
                'assigned_to' => $item['assigned_to'],
                'department' => $item['department'],
                'campaign' => $item['campaign'],
                'location' => $item['location'],
                'status' => $item['status'],
                'remarks' => $item['remarks'],
                'history' => json_encode([]),
                'file_attach' => json_encode([]),
                'quantity' => $item['quantity'],
            ]);
        }
    }
}
